services:
  daemon:
    build: .
    image: ros-ddnsd:latest
    restart: unless-stopped
    network_mode: host
    environment:
      ROS_HOST: 192.168.88.1 # 192.168.88.1 is the default gateway address, update to your default
      DNS_RECORD_NAME: router.example.com # Replace with desired DNS record name
      DNS_RECORD_ID: # Add your DNS record ID here
      DNS_ZONE_ID: # Add your DNS zone ID here
      RECORD_TTL: 60
      CHECK_INTERVAL: 30
    secrets:
      - dns_api_token
      - ros_user
      - ros_pass
secrets:
  dns_api_token:
    file: ./secrets/dns_api_token.txt
  ros_user:
    file: ./secrets/ros_user.txt
  ros_pass:
    file: ./secrets/ros_pass.txt
    
